name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker login
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      
      - name: Build Docker Image
        run: 
          docker build -t miguelrodriguezperez/docker_graphql:0.0.2 .
          docker build -t miguelrodriguezperez/docker_graphql:latest .

      - name: Push Docker Image
        run: 
          docker push miguelrodriguezperez/docker_graphql:0.0.2 
          docker push miguelrodriguezperez/docker_graphql:latest 

    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    #  Error every step must define a `uses` or `run` key
